steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--no-cache', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/f1-fantasy-league/formula1fantasy:$COMMIT_SHA', '.', '-f', 'Dockerfile' ]
  env:
  - 'DOCKER_BUILDKIT=1'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/f1-fantasy-league/formula1fantasy:$COMMIT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'[[7](https://www.google.com/url?sa=E&q=https%3A%2F%2Fvertexaisearch.cloud.google.com%2Fgrounding-api-redirect%2FAUZIYQFISvxzWCs_NUmQDoNtFWvejRuBjK1K-aqxPiPKpR00HzJkpL8CIwuELdTh6Dzflc_dz5OUBjxTT1_66BHTnYxggG0yocrqRhTv1OZPqB5jlSfBFKG3QVleu_YdNyH_OQzjixqC6MeSc1W5ejpEMIMwueLlLYRc)]
  - 'deploy'[[2](https://www.google.com/url?sa=E&q=https%3A%2F%2Fvertexaisearch.cloud.google.com%2Fgrounding-api-redirect%2FAUZIYQFkACl1glDTYDLzQmz4qqH4B92zd5aB2d7jUVMeByjhcQCJO1LejWaYCFiQqF8ssNnZXiDbTiWs2P3F0UgZcYcOMVbXXRZORrh_YNxgn-U57TDG1oJJZg6zpwhnJkY0tTbXWoSPrVGze5JoRoswPj_Wns6xHO8wOHurLs7JtI9OUkJTBJA%3D)][[4](https://www.google.com/url?sa=E&q=https%3A%2F%2Fvertexaisearch.cloud.google.com%2Fgrounding-api-redirect%2FAUZIYQFam-RqOLLC8g5yxZzmyfJd1SPuBZwMLDzG2VqCHnL8fCFlNyI13LiFWlCvm1fnOCyqkJ8HAJsK-azDULKATj6Pzcwhq-ujuV0-fTOA81dH2jMfxqqjOlzsRPardqq_H6MgXHekHx6_5Fme0iEDb19tZfwPmQ7S1Y_V9sBVNwkULy38FF8%3D)][[6](https://www.google.com/url?sa=E&q=https%3A%2F%2Fvertexaisearch.cloud.google.com%2Fgrounding-api-redirect%2FAUZIYQHXZfvmfaDsn0d2v3DS377p54MTSC6vynzcC19iX1dV90TLkrDYNJ0Q-lMWPboZjW5-z_8Ul1DHdsvkmO3q_sI_8t4DhWRl4JcW64Ql8avQXFjW3aZ2NMPX3eDiVBRyEgPr32L02sGWzluM5cKgyYWuyFSiQJcCqKph5CJTWCbuqv9NEw1fNg%3D%3D)][[7](https://www.google.com/url?sa=E&q=https%3A%2F%2Fvertexaisearch.cloud.google.com%2Fgrounding-api-redirect%2FAUZIYQFISvxzWCs_NUmQDoNtFWvejRuBjK1K-aqxPiPKpR00HzJkpL8CIwuELdTh6Dzflc_dz5OUBjxTT1_66BHTnYxggG0yocrqRhTv1OZPqB5jlSfBFKG3QVleu_YdNyH_OQzjixqC6MeSc1W5ejpEMIMwueLlLYRc)][[8](https://www.google.com/url?sa=E&q=https%3A%2F%2Fvertexaisearch.cloud.google.com%2Fgrounding-api-redirect%2FAUZIYQHPzQ2AsAQi5dtuctpgzu8TkXjzASy9_20KkGW-OQohEpUs8kWEsumyYB_Lr-AwRns6_M5FhT-M3JlkCFXEvcWHOjSiP79x6oMZxb57qC4mB_OWwpcHfYQZSHysw5UfRfjd5fc5AuhNnKCh_oT13dtDKHkVJB07svGilxLX1nIYh5BmP1obB19eEcWfb5Q%3D)]
  - 'f1-fantasy-league'
  - '--image'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/f1-fantasy-league/formula1fantasy:$COMMIT_SHA'
  - '--region'
  - 'europe-west1'

images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/f1-fantasy-league/formula1fantasy:$COMMIT_SHA'